server:
  port: 8081

spring:
  application:
    name: api_practice

  datasource:
    url: jdbc:mysql://localhost:3330/spring_class_school?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: "THIS_IS_AT_LEAST_32_BYTES_SECRET_KEY_EXAMPLE_1234"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: alpha
    tagsSorter: alpha

logging:
  level:
    org.springdoc: INFO
